import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Adekola Adedeji",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className ='scroll-smooth'>
      <body className={`bg-gray-50 scroll-smooth scrollbar-hide ${inter.className}`}>
     {children}</body>
    </html>
  );
}
